---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## First step is to use echo = TRUE so anyone can read the code.

library(knitr)
opts_chunk$set(echo = TRUE, results = 'hold')

## Then I loaded the required libraries:

library(data.table)
library(ggplot2)

## Loading and preprocessing the data

# 1. Loading the data

rdata <- read.csv('activity.csv', header = TRUE, sep = ",", colClasses=c("numeric" , "character", "numeric"))

## 2. Then the data must be tidied:

rdata$date <- as.Date(rdata$date, format = "%Y-%m-%d")
rdata$interval <- as.factor(rdata$interval)

## To check the data, I used the str() method:

str(rdata)

## What is mean total number of steps taken per day?

## 1. First I calculated the toal steps per day:

steps_per_day <- aggregate(steps ~ date, rdata, sum)
colnames(steps_per_day) <- c("date", "steps")
head(steps_per_day)

## 2. Then I created a histogram of the total number of steps taken per day.

ggplot(steps_per_day, aes(x = steps)) + geom_histogram(fill = "green", binwidth = 1000) + labs(title="Histogram of Steps Taken per Day", x = "Number of Steps per Day", y = "Number of times in a day(Count)") + theme_bw()

## To calculate the mean and median of the steps taken per day.

steps_mean   <- mean(steps_per_day$steps, na.rm=TRUE)
steps_median <- median(steps_per_day$steps, na.rm=TRUE)

## 3. The mean is 10766.189 and the meadian is 10765.

## What is the average daily activity pattern?

steps_per_interval <- aggregate(rdata$steps, 
                                by = list(interval = rdata$interval),
                                FUN=mean, na.rm=TRUE)

## (converted to integers for plotting)
steps_per_interval$interval <- 
  as.integer(levels(steps_per_interval$interval)[steps_per_interval$interval])
colnames(steps_per_interval) <- c("interval", "steps")

## 1. I made a time series plot of the 5-minute interval and the average number of steps taken, averaged across all days

ggplot(steps_per_interval, aes(x=interval, y=steps)) +   
  geom_line(color="orange", size=1) +  
  labs(title="Average Daily Activity Pattern", x="Interval", y="Number of steps") +  
  theme_bw()

## 2. Now I found which 5-minute interval (on average across all the days) contains the maximum number of steps

max_interval <- steps_per_interval[which.max(steps_per_interval$steps),]

## The 835th interval has maximum of 206 steps.

## Imputing missing values

## 1. I calculated the total number of missing values.

missing_vals <- sum(is.na(rdata$steps))

## The total number of missing values is 2304.

## 2. Strategy for filling in missing values: replace the missing values with the mean value at the same interval across days. 

na_fill <- function(data, pervalue) {
  na_index <- which(is.na(data$steps))
  na_replace <- unlist(lapply(na_index, FUN=function(idx){
    interval = data[idx,]$interval
    pervalue[pervalue$interval == interval,]$steps
  }))
  fill_steps <- data$steps
  fill_steps[na_index] <- na_replace
  fill_steps
}

rdata_fill <- data.frame(  
  steps = na_fill(rdata, steps_per_interval),  
  date = rdata$date,  
  interval = rdata$interval)
str(rdata_fill)

## Are there any missing values remaining?

sum(is.na(rdata_fill$steps))

## The output is zero so there are no missing values.

## 4. Make a histogram then report the mean and median total number of steps taken per day. 

## This step is to create the data set without the missing values.
fill_steps_per_day <- aggregate(steps ~ date, rdata_fill, sum)
colnames(fill_steps_per_day) <- c("date","steps")

##plotting the histogram
ggplot(fill_steps_per_day, aes(x = steps)) + 
  geom_histogram(fill = "blue", binwidth = 1000) + 
  labs(title="Histogram of Steps Taken per Day", 
       x = "Number of Steps per Day", y = "Number of times in a day(Count)") + theme_bw() 

steps_mean_fill   <- mean(fill_steps_per_day$steps, na.rm=TRUE)
steps_median_fill <- median(fill_steps_per_day$steps, na.rm=TRUE)

## The mean is 10766.189 and the median is 10766.189. These values differ slightly from the first part of the assignment. The median before was 10765 and after filling the data it was 10766.189. Without missing data, the mean remains unchanged but the median has shifted. Inputing missing values increases the peak but doesn't affect our predictions.

## Are there differences in activity patterns between weekdays and weekends?

## 1. Distinguish whether a day is a weekday or weekend.

weekdays_steps <- function(data) {
  weekdays_steps <- aggregate(data$steps, by=list(interval = data$interval),
                              FUN=mean, na.rm=T)
  # convert to integers for plotting
  weekdays_steps$interval <- 
    as.integer(levels(weekdays_steps$interval)[weekdays_steps$interval])
  colnames(weekdays_steps) <- c("interval", "steps")
  weekdays_steps
}

data_by_weekdays <- function(data) {
  data$weekday <- 
    as.factor(weekdays(data$date)) # weekdays
  weekend_data <- subset(data, weekday %in% c("Saturday","Sunday"))
  weekday_data <- subset(data, !weekday %in% c("Saturday","Sunday"))
  
  weekend_steps <- weekdays_steps(weekend_data)
  weekday_steps <- weekdays_steps(weekday_data)
  
  weekend_steps$dayofweek <- rep("weekend", nrow(weekend_steps))
  weekday_steps$dayofweek <- rep("weekday", nrow(weekday_steps))
  
  data_by_weekdays <- rbind(weekend_steps, weekday_steps)
  data_by_weekdays$dayofweek <- as.factor(data_by_weekdays$dayofweek)
  data_by_weekdays
}

data_weekdays <- data_by_weekdays(rdata_fill)

## 2. Make a Panel plot.

ggplot(data_weekdays, aes(x=interval, y=steps)) + 
  geom_line(color="violet") + 
  facet_wrap(~ dayofweek, nrow=2, ncol=1) +
  labs(x="Interval", y="Number of steps") +
  theme_bw()

